account/urls.py
from django.urls import path

from account.views import (
        login_view,
        staff_register_view,
        student_register_view,
        logout_view,
    )

app_name = "account"

urlpatterns = [
    path('', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('staff-register/', staff_register_view, name="staff-register"),
    path('student-register/', student_register_view, name="student-register"),
]

api/urls.py
from django.urls import path

from api.views import (
		get_question,
	)

urlpatterns = [
	path('question/<str:pk>/', get_question, name="question"),
]

cbt/urls.py
# MAIN URL ROUTES

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import (
        PasswordResetView,
        PasswordResetDoneView,
        PasswordResetConfirmView,
        PasswordResetCompleteView,
    )

urlpatterns = [
    path('', include('account.urls', 'account')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', 'dashboard')),
    path('api/', include('api.urls')),


    path('reset_password/', 
        PasswordResetView.as_view(template_name="account/password-reset.html"), 
        name="password_reset"),

    path('reset_password_sent/', 
        PasswordResetDoneView.as_view(template_name="account/password-reset-sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(template_name="account/password-reset-confirm.html"), 
        name="password_reset_confirm"),

    path('reset-password_complete/', 
        PasswordResetCompleteView.as_view(template_name="account/password-reset-complete.html"), 
        name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include

# from dashboard.views import admin_dashboard

app_name = 'dashboard'

urlpatterns = [
	path('student/', include('dashboard.urls_manager.student_urls', 'student')),
	path('lecturer/', include('dashboard.urls_manager.lecturer_urls', 'lecturer')),
	# path('admin/', admin_dashboard, name="admin-dashboard"),
]

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from dashboard.views_manager.lecturer_view_manager import questions

from dashboard.views_manager.student_view_manager import tests_view


@login_required
def lecturer_dashboard(request, *args, **kwargs):
	context = {}
	return questions(request)

@login_required
def student_dashboard(request, *args, **kwargs):
	return tests_view(request)

dashboard/templates/dashboard/admin-dashboard.html
<h2>Admin Dashboard</h2>

{{ request.user }}

dashboard/templates/dashboard/dashboard.html
{% extends 'main.html' %}


  {% block content %}

  	<section id="menu">
  		


  	</section>

  	<section id="interface">
  		

  		
  	</section>

  {% endblock content %}

dashboard/templates/dashboard/lecturer-dashboard.html
{% extends 'main.html' %}

{% load static %}


  {% block content %}

    <section id="menu">

      <div class="user-detail">
        <img src="{{ request.user.lecturer.imageURL }}">
        <div class="user-info">
          <h2>{{ request.user.first_name | title }} {{ request.user.last_name | title }}</h3>
          <h3>[{{ request.user.username | upper}}]</h3>
        </div>
      </div>

      <div class="nav">
        <li>
          <i class="fa-solid fa-file-pen"></i>
          <a href="{% url 'dashboard:lecturer:questions' %}">Questions</a>
        </li>
        <li>
          <i class="fa-solid fa-check-to-slot"></i>
          <a href="{% url 'dashboard:lecturer:show-result' %}">Show Results</a>
        </li>
        <li>
          <i class="fa-solid fa-marker"></i>
          <a href="{% url 'dashboard:lecturer:attendance' %}">Attendance</a>
        </li>
        <li>
          <i class="fa-solid fa-file-arrow-down"></i>
          <a href="{% url 'dashboard:lecturer:download-result' %}">Download Result</a>
        </li>
        <li>
          <i class="fa-solid fa-right-from-bracket"></i>
          <a href="{% url 'account:logout' %}">Logout</a>
        </li>
      </div>

    </section>



    <section id="interface">
      
      <div class="bar">
        <div>
          <i id="menu-btn" class="fas fa-bars"></i>
        </div>
        <div class="status">
          <img src="{% static 'img/logo.png' %}">
        </div>
      </div>

                  
      <div id="interface-board" class="available-test">
        
        {% block elements %}


        {% endblock elements %}

      </div>
        
    </section>



    <script type="text/javascript">
      $('#menu-btn').click(function(){
        $('#menu').toggleClass('active')
      })
    </script>

  {% endblock content %}

dashboard/templates/dashboard/student-dashboard.html
{% extends 'main.html' %}

{% load static %}


  {% block content %}

  	<section id="menu">

  		<div class="user-detail">
  			<img src="{{ request.user.student.imageURL }}">
  			<div class="user-info">
  				<h2>{{ request.user.first_name | title }} {{ request.user.last_name | title }}</h3>
  				<h3>[{{ request.user.username | upper}}]</h3>
  			</div>
  		</div>

  		<div class="nav">
  			<li>
  				<i class="fa-solid fa-file-pen"></i>
  				<a href="{% url 'dashboard:student:tests' %}">Write Test</a>
  			</li>
  			<li>
  				<i class="fa-solid fa-check-to-slot"></i>
  				<a href="{% url 'dashboard:student:result' %}">Check Result</a>
  			</li>
  			<li>
  				<i class="fa-solid fa-print"></i>
  				<a href="{% url 'dashboard:student:print-result' %}">Print Result</a>
  			</li>
  			<li>
  				<i class="fa-solid fa-right-from-bracket"></i>
  				<a href="{% url 'account:logout' %}">Logout</a>
  			</li>
  		</div>

  	</section>



  	<section id="interface">
  		
  		<div class="bar">
  			<div>
  				<i id="menu-btn" class="fas fa-bars"></i>
  			</div>
  			<div class="status">
  				<div class="notification">
  					<a href="#">
  						<i class="far fa-bell"></i>
  						<span>9</span>
  					</a>
  				</div>
  				<img src="{% static 'img/logo.png' %}">
  			</div>
  		</div>

                  
      <div id="interface-board" class="available-test">
        
        {% block elements %}


        {% endblock elements %}

      </div>
        
  	</section>



  	<script type="text/javascript">
  		$('#menu-btn').click(function(){
  			$('#menu').toggleClass('active')
  		})
  	</script>

  {% endblock content %}